version: '3.8'

services:
  db:
    container_name: postgres-db
    image: postgres:latest
    environment:
      POSTGRES_DB: monitoring-service-db
      POSTGRES_USER: trapper
      POSTGRES_PASSWORD: 9qwe1ox
    ports:
      - "5433:5432"