###REGISTRATION
POST {{url}}/api/v2/users/register
Content-Type: application/json

{
  "username": "trapper123",
  "password": "trapper"
}

###AUTHENTICATION
POST {{url}}/api/v2/users/authenticate
Content-Type: application/json

{
  "username": "root",
  "password": "root"
}

###SUBMIT
POST {{url}}/api/v2/readings/submit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "HOT",
  "reading": 1,
  "month": "January",
  "year": "2020"
}

###GET CURRENT READINGS
GET {{url}}/api/v2/readings/current
Content-Type: application/json
Authorization: Bearer {{token}}

###GET MONTHLY READINGS
GET {{url}}/api/v2/readings/monthly?month=January&year=201
Content-Type: application/json
Authorization: Bearer {{token}}

###HISTORY
GET {{url}}/api/v2/readings/history
Content-Type: application/json
Authorization: Bearer {{token}}

###RIGHTS
POST {{url}}/api/v2/admins/rights
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "trapper123",
  "action": "upgrade"
}

###AUDIT
GET {{url}}/api/v2/admins/audit
Content-Type: application/json
Authorization: Bearer {{token}}